# Server configurations
server:
  host: "localhost"
  port: 8000

# Database credentials
database:
  name: "bank_transactions"
  host: "127.0.0.1"
  user: "pimenta"
  pass: "pimenta001"
  port: 3399

api:
  limit: 200

  auth:
    client_id: "dc97438a-8340-4e8f-a603-dbfafe12adc4"
    client_secret: "AKdu5LhWwUjENfKwhDZ2OdQpo6QWaq_zJudO2rE25EHkP_ibvoeE8ckpd6cvXhJywPZZkndIVg7evLA46jSFSTY"
    code: "k7WYWb"
    redirect_uri: "http://pimenta:3000/"

  get_token:
    method: "POST"
    uri: "https://simulator-api.db.com/gw/oidc/token"

  get_transaction:
    method: "GET"
    uri: "https://simulator-api.db.com:443/gw/dbapi/banking/transactions/v2"

  get_accounts:
    method: "GET"
    uri: "https://simulator-api.db.com/gw/dbapi/banking/cashAccounts/v2"
