package main

type BANK_PROBLEM struct {
	BANK_TRANSACTION_PROBLEM_VENDOR_UNDEFINED                  string
	BANK_TRANSACTION_PROBLEM_CLIENT_UNDEFINED                  string
	BANK_TRANSACTION_PROBLEM_EXPENSE_NOT_FOUND                 string
	BANK_TRANSACTION_PROBLEM_PAYMENT_NOT_FOUND                 string
	BANK_TRANSACTION_PROBLEM_CHARGEBACK_NOT_FOUND              string
	BANK_TRANSACTION_PROBLEM_PAYMENT_FACTORY_NOT_FOUND         string
	BANK_TRANSACTION_PROBLEM_PAYMENT_FACTORY_INVOICE_NOT_FOUND string
	BANK_TRANSACTION_PROBLEM_PAYMENT_FACTORY_VENDOR_NOT_FOUND  string
	BANK_TRANSACTION_PROBLEM_CHARGEBACK_CLIENT_NOT_FOUND       string
	BANK_TRANSACTION_PROBLEM_CHARGEBACK_VENDOR_NOT_FOUND       string
	BANK_TRANSACTION_RELATION_STATUS_AUTO                      string
	BANK_TRANSACTION_RELATION_STATUS_CONFIRMED                 string
	BANK_TRANSACTION_RELATION_STATUS_DENIED                    string
}

func BANK_TRANSACTION_PROBLEM() BANK_PROBLEM {

	return BANK_PROBLEM{
		BANK_TRANSACTION_PROBLEM_VENDOR_UNDEFINED:                  "vendor_undefined",
		BANK_TRANSACTION_PROBLEM_CLIENT_UNDEFINED:                  "client_undefined",
		BANK_TRANSACTION_PROBLEM_EXPENSE_NOT_FOUND:                 "expense_not_found",
		BANK_TRANSACTION_PROBLEM_PAYMENT_NOT_FOUND:                 "payment_not_found",
		BANK_TRANSACTION_PROBLEM_CHARGEBACK_NOT_FOUND:              "chargeback_not_found",
		BANK_TRANSACTION_PROBLEM_PAYMENT_FACTORY_NOT_FOUND:         "payment_factory_not_found",
		BANK_TRANSACTION_PROBLEM_PAYMENT_FACTORY_INVOICE_NOT_FOUND: "payment_factory_invoice_not_found",
		BANK_TRANSACTION_PROBLEM_PAYMENT_FACTORY_VENDOR_NOT_FOUND:  "payment_factory_vendor_not_found",
		BANK_TRANSACTION_PROBLEM_CHARGEBACK_CLIENT_NOT_FOUND:       "chargeback_client_not_found",
		BANK_TRANSACTION_PROBLEM_CHARGEBACK_VENDOR_NOT_FOUND:       "chargeback_vendor_not_found",
		BANK_TRANSACTION_RELATION_STATUS_AUTO:                      "auto",
		BANK_TRANSACTION_RELATION_STATUS_CONFIRMED:                 "confirmed",
		BANK_TRANSACTION_RELATION_STATUS_DENIED:                    "denied",
	}
}
